// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcplug

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlugClient is the client API for Plug service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlugClient interface {
	SayHello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRes, error)
}

type plugClient struct {
	cc grpc.ClientConnInterface
}

func NewPlugClient(cc grpc.ClientConnInterface) PlugClient {
	return &plugClient{cc}
}

func (c *plugClient) SayHello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRes, error) {
	out := new(HelloRes)
	err := c.cc.Invoke(ctx, "/Plug/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlugServer is the server API for Plug service.
// All implementations must embed UnimplementedPlugServer
// for forward compatibility
type PlugServer interface {
	SayHello(context.Context, *HelloReq) (*HelloRes, error)
	mustEmbedUnimplementedPlugServer()
}

// UnimplementedPlugServer must be embedded to have forward compatible implementations.
type UnimplementedPlugServer struct {
}

func (UnimplementedPlugServer) SayHello(context.Context, *HelloReq) (*HelloRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedPlugServer) mustEmbedUnimplementedPlugServer() {}

// UnsafePlugServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlugServer will
// result in compilation errors.
type UnsafePlugServer interface {
	mustEmbedUnimplementedPlugServer()
}

func RegisterPlugServer(s grpc.ServiceRegistrar, srv PlugServer) {
	s.RegisterService(&Plug_ServiceDesc, srv)
}

func _Plug_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlugServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plug/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlugServer).SayHello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Plug_ServiceDesc is the grpc.ServiceDesc for Plug service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plug_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Plug",
	HandlerType: (*PlugServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Plug_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "g.proto",
}
